<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>GameScripts</AssemblyName>
    <RootNamespace>GameScripts</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <OutputPath>$(MSBuildThisFileDirectory)..\..\.elintria\ScriptsBin\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ElintriaEngine">
      <HintPath>..\..\..\..\ElintriaEngine\bin\Release\net10.0\ElintriaEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="**\*.cs" />
  </ItemGroup>

</Project>
